language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - cd ..
  - composer create --dev larapress-cms/larapress:dev-feature/package larapress
  - rm -rf larapress/vendor/larapress-cms/core
  - cp -rf core larapress/vendor/larapress-cms/core
  - cd larapress
  - php artisan dump-autoload

script: phpunit -c larapress.phpunit.xml
