language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer create --dev larapress-cms/larapress:dev-feature/package larapress
  - cd larapress
  - rm -rf vendor/larapress-cms/core
  - git clone https://github.com/larapress-cms/core.git vendor/larapress-cms/core
  - php artisan dump-autoload
  - phpunit -c larapress.phpunit.xml --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script: phpunit -c larapress.phpunit.xml
